### ISSUE TITLE
Protobuf

### ISSUE THREAD

**Issue by BboyKeen** [subzerobo/elastic-apm-php-agent#2]
Hi,

Thanks for the awesome work.
I'm trying to use your library and I'm wondering where did you found that you can use Protobuf with the APM Server ?

I can't find any information in the ELK documentation. The only mention concerns logstash.

Thanks

**Comment by subzerobo** [comment]
Hi,

Thank you, unfortunately, ELK does not support the Protobuf or even the UDP because normally the APM is used in non-scripting languages like golang, nodejs,... which support concurrency in our project it was a huge load of TCP API calls to the APM server so in this project I did 2 things

1- Upgraded the only PHP client (unofficial) to the intake API v2 so you can use it in your project
2- Created a [golang side-car](https://github.com/subzerobo/elastic-apm-go-sidecar), so the elastic-php-agent will create a UDP protobuf payload and sends it to the side-car application and it will deliver the message through TCP Http call to the elastic APM, nothing changed in the APM side! ( instead, you will not have to wait for the API call at the end of PHP process before returning the response to the user)

hope it will answer your question

Regards

**Comment by subzerobo** [comment]
> Hi,
> 
> Thanks for the awesome work.
> I'm trying to use your library and I'm wondering where did you found that you can use Protobuf with the APM Server ?
> 
> I can't find any information in the ELK documentation. The only mention concerns logstash.
> 
> Thanks

Hi,

Thank you, unfortunately, ELK does not support the Protobuf or even the UDP because normally the APM is used in non-scripting languages like golang, nodejs,... which support concurrency in our project it was a huge load of TCP API calls to the APM server so in this project I did 2 things

1- Upgraded the only PHP client (unofficial) to the intake API v2 so you can use it in your project
2- Created a [golang side-car](https://github.com/subzerobo/elastic-apm-go-sidecar), so the elastic-php-agent will create a UDP protobuf payload and sends it to the side-car application and it will deliver the message through TCP Http call to the elastic APM, nothing changed in the APM side! ( instead, you will not have to wait for the API call at the end of PHP process before returning the response to the user)

hope it will answer your question

Regards

**Comment by BboyKeen** [comment]
Hi,

That's what I thought after digging in your project. Thanks for the confirmation.

However, I'm not able to use the Intake API v2 because no matter which one I choose (UDP or TCP) the library is always using Protobuf Internals to build the transaction content even if Protobuf is disabled.

Am I missing something in the configuration ?

Thanks

**Comment by subzerobo** [comment]
Hi,

Yep, I am using protobuf internal to build the transaction anyway but the protobuf configuration is there to enable how you are sending the data to the sidecar.
So if you enable the UDP and enable the protobuf, it would send the payload using protobuf to sidecar using protobuf and when you disable the protobuf it would send the data in NDJSON format to the sidecar.

So you have 2 path

1. `defaultConnector = tcp` -> no need to use the sidecar it will send using ndjson directly to the APM server
2. `defaultConnector = udp and udpUseProto=true`  -> it would send data to side-car using protobuf
3. `defaultConnector = udp and udpUseProto=false`  -> it would send data to side-car using ndjson

Hope it helps
Regards


> Hi,
> 
> That's what I thought after digging in your project. Thanks for the confirmation.
> 
> However, I'm not able to use the Intake API v2 because no matter which one I choose (UDP or TCP) the library is always using Protobuf Internals to build the transaction content even if Protobuf is disabled.
> 
> Am I missing something in the configuration ?
> 
> Thanks

**Comment by BboyKeen** [comment]
Thanks,
I have a better understanding now. 
So the error I meet is not directly connected to Protobuf. I will open another issue to avoid mixing things.
